FROM node:21-alpine

# Set working directory
WORKDIR /Ecommerce_frontend

# Copy the package.json and package-lock.json files
COPY ./client/package.json ./client/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY ./client .

# Build the Next.js application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the Next.js server
CMD ["npm", "start"]
